# [global]
# address = "1.2.3.4"
# limits = { forms = 131072 }

[global.databases]
postgre_logs = { url = "/migrations/" }

[development]
address = "localgost"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
secret_key = ["localgost"]
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
secret_key = ["net"]
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "critical"
secret_key = ["net"]
limits = { forms = 32768 }